[project]
name = "cancer-sim"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.10.8",
    "numpy>=2.4.2",
    "pre-commit>=4.5.1",
]

[tool.ruff.lint]
select = ["F", "I", "B", "UP"]
